// import Image from 'next/image'
import Head from 'next/head'

import HeroComponent from '~/components/Hero'

function Home() {
  return (
    <div>
      <Head>
        <title>Spin Labs: A Sokoplace Group Company</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroComponent />
    </div>
  )
}

export default Home
