// import Image from 'next/image'
import Head from 'next/head'
// Sections
import HeroComponent from '~/components/Hero'
import Who from '~/components/Who'
import Services from '~/components/Services'
import Clients from '~/components/Clients'
import CTA from '~/components/CTA'

function Home() {
  return (
    <div>
      {/* Head */}
      <Head>
        <title>Spin Labs: A Sokoplace Group Company</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Hero */}
      <HeroComponent />

      {/* Who */}
      <Who />

      {/* Services */}
      <Services />

      {/* Clients */}
      <Clients />

      {/* CTA  */}
      <CTA />
    </div>
  )
}

export default Home
